apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-nodejs
spec:
  selector:
    matchLabels:
      app: sample-app-nodejs
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-app-nodejs
    spec:
      containers:
      - name: sample-app-nodejs
        image: index.docker.io/starkandwayne/sample-app-nodejs@sha256:51e5e43cf211580ed0aafbf6773683fc91292bd112cd72313a020c9229ca8532
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-nodejs
spec:
  selector:
    app: sample-app-nodejs
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
