apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: sample-app-nodejs
spec:
  builderRef: cflinuxfs3-builder
  serviceAccount: service-account
  cacheSize: "1.5Gi"
  source:
    git:
      url: https://github.com/starkandwayne/sample-app-nodejs.git
      revision: master
  tag: starkandwayne/sample-app-nodejs:latest


