apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: sample-app-nodejs
spec:
  tag: starkandwayne/sample-app-nodejs
  builderRef: cloudfoundry/cnb:cflinuxfs3
  serviceAccount: service-account
  source:
    git:
      url: https://github.com/starkandwayne/sample-app-nodejs.git
      revision: master
