# fly -t ohio-drnic sp -p sample-app-nodejs -c ci/pipeline-new-builder.yml \
#     -v pack-builder-image=cloudfoundry/cnb -v pack-builder-tag=cflinuxfs3 \
#     -v image=starkandwayne/sample-app-nodejs

resource_types:
- name: pack-image-resource
  type: docker-image
  privileged: true
  source:
    repository: bstick12/pack-concourse-resource

resources:
- name: git
  type: git
  source:
    uri: https://github.com/starkandwayne/sample-app-nodejs.git
- name: image
  type: pack-image-resource
  source:
    repository: ((image))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
- name: builder-image
  type: docker-image
  check_every: 1h
  source:
    repository: ((pack-builder-image))
    tag: ((pack-builder-tag))

jobs:
- name: build-image
  plan:
  - get: git
    trigger: true
  - get: builder-image
    trigger: true
    params: {skip_download: true}
  - put: image
    params:
      build: git
      builder: ((pack-builder-image)):((pack-builder-tag))

